this version does not work because of the error of handleSubmit handler at CommentForm. error is Uncaught TypeError: React.findDOMNode is not a function